# =============== 站点基本信息 ===============
site_name: ZUTOMATO
site_url: https://mydomain.org/mysite

# =============== 主题配置 ===============
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: deep purple
      accent: blue
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: deep purple
      accent: blue

  language: zh
  logo: https://s21.ax1x.com/2025/07/19/pV3XuZ9.png
  favicon: https://s21.ax1x.com/2025/07/19/pV3XuZ9.png

  features:
    - announce.dismiss
    - navigation.instant
    - header.autohide
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - navigation.expand
    - navigation.indexes
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.math.mathjax

  icon:
    repo: fontawesome/brands/github
    logo: logo

# =============== 插件 ===============
plugins:
  - search
  - blog

# =============== Markdown 扩展（新增） ===============
markdown_extensions:
  - pymdownx.arithmatex:   # 识别 $...$ / $$...$$
      generic: true

# =============== 静态资源（新增） ===============
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://mirrors.pku.edu.cn/CTAN/systems/texlive/tlnet/2023/tlpkg/tlperl/tex-mml-chtml.min.js

# =============== 导航 ===============
nav:
  - 主页: index.md
  - 关于我: md/profile.md
  - 我的课程总结:
      - 统计学/数学:
          - 数学分析: md/note/math/数学分析.md
          - 高等代数与解析几何: md/note/math/高等代数与解析几何.md
          - 概率论: md/note/math/概率论.md
          - 实变函数: md/note/math/实变函数.md
          - 数理统计: md/note/math/数理统计.md
          - 随机过程: md/note/math/随机过程.md
          - 常微分方程: md/note/math/常微分方程.md
      - 化学:
          - 无机化学: md/note/chemistry/无机化学.md
          - 有机化学1: md/note/chemistry/有机化学1.md
          - 有机化学2: md/note/chemistry/有机化学2.md
          - 分析化学1: md/note/chemistry/分析化学1.md
          - 分析化学2: md/note/chemistry/分析化学2.md
          - 结构与谱学1（现已改为结构化学1）: md/note/chemistry/结构与谱学.md
          - 普通化学实验: md/note/chemistry/普通化学实验.md
  - 我的课程笔记: md/notes.md
  - 编曲/混音: 
    - 瞎写的一些东西: md/music/demo.md
    - 混音: md/music/混音.md