# 1. 站点信息
site_name: ZUTOMATO
site_url: https://mydomain.org/mysite

# 2. 主题
theme:
  name: material
  features:
    - content.math.mathjax   # 关键：打开 Material 内置 MathJax
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  language: zh
  logo: https://s21.ax1x.com/2025/07/19/pV3XuZ9.png
  favicon: https://s21.ax1x.com/2025/07/19/pV3XuZ9.png

# 3. 插件
plugins:
  - search
  - blog

# 4. Markdown 扩展
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true   # 让 $ ... $ 直接生效

# 5. 国内 CDN（避免被墙）
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js

# 6. 导航
nav:
  - 主页: index.md
  - 关于我: md/profile.md
  - 我的课程总结:
      - 统计学/数学:
          - 数学分析: md/note/math/数学分析.md
          - 高等代数与解析几何: md/note/math/高等代数与解析几何.md
          - 概率论: md/note/math/概率论.md
          - 实变函数: md/note/math/实变函数.md
          - 数理统计: md/note/math/数理统计.md
          - 随机过程: md/note/math/随机过程.md
          - 常微分方程: md/note/math/常微分方程.md
      - 化学:
          - 无机化学: md/note/chemistry/无机化学.md
          - 有机化学1: md/note/chemistry/有机化学1.md
          - 有机化学2: md/note/chemistry/有机化学2.md
          - 分析化学1: md/note/chemistry/分析化学1.md
          - 分析化学2: md/note/chemistry/分析化学2.md
          - 结构与谱学1（现已改为结构化学1）: md/note/chemistry/结构与谱学.md
          - 普通化学实验: md/note/chemistry/普通化学实验.md
  - 我的课程笔记: md/notes.md
  - 我的编曲/混音日记: md/arranging.md