site_name: ZUTOMATO
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    #primary: deep purple
    #accent: deep blue
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        primary: deep purple
        accent: blue

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        primary: deep purple
        accent: blue
  language: zh
  logo: https://s21.ax1x.com/2025/07/19/pV3XuZ9.png
  favicon: https://s21.ax1x.com/2025/07/19/pV3XuZ9.png
  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.instant
    - header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github #右上角图标
    logo: logo
plugins:
  - search
  - blog
nav: 
  - 主页: index.md
  - 关于我: md/profile.md
  - 我的课程总结:
      - 统计学/数学:
        - 数学分析: md/note/math/数学分析.md
        - 高等代数与解析几何: md/note/math/高等代数与解析几何.md
        - 概率论: md/note/math/概率论.md
        - 实变函数: md/note/math/实变函数.md
        - 数理统计: md/note/math/数理统计.md
        - 随机过程: md/note/math/随机过程.md
        - 常微分方程: md/note/math/常微分方程.md
      - 化学:
        - 无机化学: md/note/chemistry/无机化学.md
        - 有机化学1: md/note/chemistry/有机化学1.md
        - 有机化学2: md/note/chemistry/有机化学2.md  
        - 分析化学1: md/note/chemistry/分析化学1.md
        - 分析化学2: md/note/chemistry/分析化学2.md
        - 结构与谱学1（现已改为结构化学1）: md/note/chemistry/结构与谱学.md
        - 普通化学实验: md/note/chemistry/普通化学实验.md
  - 我的课程笔记:
    - md/notes.md
  - 我的编曲/混音日记:
    - md/arranging.md